title: testopenzfs
description: best filesystem

exclude: [
            package.json,
            bower.json,
            grunt.js,
            Gruntfile.js,
            node_modules,
            bower_components,
            validation-report.json,
            validation-status.json,
            scripts.js,
            scripts.tmp.min.js,
            style.css,
            style.tmp.min.css,
            lgoo.psd,
            Makefile,
            exclude.rsync,
            README.markdown
         ]

google_tracking_id:

theme: jekyll-theme-cayman
